import type { Metadata, Viewport } from "next";
import { UnifrakturCook } from "next/font/google";
import "./globals.css";

const heroNameFont = UnifrakturCook({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-hero-name",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${heroNameFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
